$(document).ready(function(){
    $('#hide').click(function(){
        $('div.center').hide('slow');
    });
    $('#show').click(function(){
        $('div.center').show('fast');
    });
    $('#toggle').click(function(){
        $('div.center').toggle(500);
    });
    $('#fadein').click(function(){
        $('div.center').fadeIn('fast');
    });
    $('#fadeout').click(function(){
        $('div.center').fadeOut('slow');
    });
    $('#fadetoggle').click(function(){
        $('div.center').fadeToggle(500);
    });
    $('#fadeto').click(function(){
        $('div.center').fadeTo(1000,0.5);
    });
    $('#slidedown').click(function(){
        $('div.center').slideDown('slow');
    });
    $('#slideup').click(function(){
        $('div.center').slideUp('fast');
    });
    $('#slidetoggle').click(function(){
        $('div.center').slideToggle(500);
    });
    $('#animate').click(function(){
        /*var cdiv=$('div.center');
        cdiv.animate({
            left:'20%'
        },'slow');
        cdiv.animate({
            left:'50%'
        },'fast');*/
        $('div.center').animate({
            left:'20%'
        },'slow',function(){
            console.log('animate')
        }).animate({
            left:'50%'
        },'slow');
        console.log('log');
        $('div.test_div').animate({
            left:'80%'
        });
    
    });
    console.log($('#get').text());
    console.log($('#get').html());
    $('#remove').click(function(){
        $('#p1').empty('.child');
    })
});